@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jul 01 13:09:51 +0200 2026
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_system_behav -key {Behavioral:sim_1:Functional:tb_system} -tclbatch tb_system.tcl -protoinst "protoinst_files/system.protoinst" -view D:/Xilinx/RedPitaya/prj/v0.94/Red-Pitaya-Projects/pid_piezo/pid_piezo.sim/tb_pid_soft_out_behav.wcfg -log simulate.log"
call xsim  tb_system_behav -key {Behavioral:sim_1:Functional:tb_system} -tclbatch tb_system.tcl -protoinst "protoinst_files/system.protoinst" -view D:/Xilinx/RedPitaya/prj/v0.94/Red-Pitaya-Projects/pid_piezo/pid_piezo.sim/tb_pid_soft_out_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
