@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 29 10:27:25 +0200 2026
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim test_bench_behav -key {Behavioral:sim_1:Functional:test_bench} -tclbatch test_bench.tcl -protoinst "protoinst_files/system.protoinst" -view D:/Xilinx/RedPitaya/prj/v0.94/Red-Pitaya-Projects/piezo_resonance_test/piezo_resonance_test.srcs/sim_1/imports/DAC_ACD_test_project/test_bench_behav.wcfg -log simulate.log"
call xsim  test_bench_behav -key {Behavioral:sim_1:Functional:test_bench} -tclbatch test_bench.tcl -protoinst "protoinst_files/system.protoinst" -view D:/Xilinx/RedPitaya/prj/v0.94/Red-Pitaya-Projects/piezo_resonance_test/piezo_resonance_test.srcs/sim_1/imports/DAC_ACD_test_project/test_bench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
