# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/RedPitaya/sdc/red_pitaya.xdc

# XDC: imports/RedPitaya/prj/v0.94/sdc/red_pitaya.xdc

# Block Designs: bd/ps_system/ps_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system || ORIG_REF_NAME==ps_system} -quiet] -quiet

# IP: bd/ps_system/ip/ps_system_processing_system7_0_0/ps_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_processing_system7_0_0 || ORIG_REF_NAME==ps_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_system/ip/ps_system_ps7_0_axi_periph_0/ps_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==ps_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_rst_M_AXI_GP0_ACLK_0_100M_0 || ORIG_REF_NAME==ps_system_rst_M_AXI_GP0_ACLK_0_100M_0} -quiet] -quiet

# IP: bd/ps_system/ip/ps_system_Reg_Network_Connect_0_2/ps_system_Reg_Network_Connect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_Reg_Network_Connect_0_2 || ORIG_REF_NAME==ps_system_Reg_Network_Connect_0_2} -quiet] -quiet

# IP: bd/ps_system/ip/ps_system_auto_pc_0/ps_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_auto_pc_0 || ORIG_REF_NAME==ps_system_auto_pc_0} -quiet] -quiet

# XDC: bd/ps_system/ps_system_ooc.xdc
