# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0.xci
# IP: The module: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0.xci
# IP: The module: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Gaming/Documents/fpga_projects/RedPitaya/prj/v0.94/First_test_project/redpitaya.srcs/sources_1/bd/ps_system/ip/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0/ps_system_rst_M_AXI_GP0_ACLK_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_M_AXI_GP0_ACLK_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
