@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 08 21:28:01 +0200 2026
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_core_logic_behav -key {Behavioral:sim_1:Functional:tb_core_logic} -tclbatch tb_core_logic.tcl -protoinst "protoinst_files/system.protoinst" -view D:/Xilinx/RedPitaya/prj/v0.94/Red-Pitaya-Projects/DAC_ACD_test_project/tb_core_logic_behav.wcfg -log simulate.log"
call xsim  tb_core_logic_behav -key {Behavioral:sim_1:Functional:tb_core_logic} -tclbatch tb_core_logic.tcl -protoinst "protoinst_files/system.protoinst" -view D:/Xilinx/RedPitaya/prj/v0.94/Red-Pitaya-Projects/DAC_ACD_test_project/tb_core_logic_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
